"""Stable versions, tokens, and exit codes."""

from __future__ import annotations

VERSION = "0.1.0"
ENVELOPE_VERSION = 1
SEAM_MAP_VERSION = 1
DELIVERY_PLAN_VERSION = 1
TASK_GRAPH_VERSION = 1
TASK_SPEC_FORMAT_VERSION = 3
AGENT_CONTRACT_VERSION = 2

EXIT_OK = 0
EXIT_NEEDS_INPUT = 2
EXIT_INVALID = 3
EXIT_CONFLICT = 4
EXIT_UNAVAILABLE = 5
EXIT_INTERNAL = 10

SEAM_READY = "SEAM_MAP=READY"
SEAM_NEEDS_DISCOVERY = "SEAM_MAP=NEEDS_DISCOVERY"
SEAM_NEEDS_OWNER = "SEAM_MAP=NEEDS_OWNER_INPUT"
SEAM_NEEDS_DECISION = "SEAM_MAP=NEEDS_ARCHITECTURE_DECISION"
SEAM_AMBIGUOUS = "SEAM_MAP=AMBIGUOUS"
SEAM_ERROR = "SEAM_MAP=ERROR"

PLAN_READY = "DELIVERY_PLAN=READY"
PLAN_NEEDS_REVIEW = "DELIVERY_PLAN=NEEDS_REVIEW"
PLAN_OPEN_OBJECTIONS = "DELIVERY_PLAN=OPEN_OBJECTIONS"
PLAN_NEEDS_OWNER = "DELIVERY_PLAN=NEEDS_OWNER_INPUT"
PLAN_NEEDS_DECISION = "DELIVERY_PLAN=NEEDS_ARCHITECTURE_DECISION"
PLAN_ERROR = "DELIVERY_PLAN=ERROR"

GRAPH_READY = "TASK_GRAPH=READY"
GRAPH_CYCLE = "TASK_GRAPH=CYCLE"
GRAPH_COLLISION = "TASK_GRAPH=COLLISION"
GRAPH_UNPROVABLE = "TASK_GRAPH=UNPROVABLE_NODE"
GRAPH_BLOCKED = "TASK_GRAPH=BLOCKED"
GRAPH_ERROR = "TASK_GRAPH=ERROR"

SPECS_EMITTED = "TASK_SPECS=EMITTED"
SPECS_VALID = "TASK_SPECS=VALID"
SPECS_PREFLIGHT = "TASK_SPECS=PREFLIGHT_READY"
SPECS_SEALED = "TASK_SPECS=SEALED"
SPECS_INVALID = "TASK_SPECS=INVALID"
SPECS_ERROR = "TASK_SPECS=ERROR"

INIT_READY = "WORKSPACE=READY"
STATUS_READY = "STATUS=READY"
STATUS_BLOCKED = "STATUS=BLOCKED"
DOCTOR_OK = "DOCTOR=OK"
DOCTOR_BLOCKED = "DOCTOR=BLOCKED"
INSTALL_OK = "INSTALL=OK"
UNINSTALL_OK = "UNINSTALL=OK"
REPORT_READY = "REPORT=READY"
CONTEXT_READY = "AGENT_CONTEXT=READY"
